[versions]
androidxActivity = "1.12.2"
androidxAnnotation = "1.9.1"
androidxBiometric = "1.1.0"
androidxBrowser = "1.9.0"
androidxConstraintlayout = "2.2.1"
androidxCredentials = "1.5.0"
androidxDatastorePreferences = "1.2.0"
androidxSqlite = "2.6.2"
androidxTest = "1.7.0"
androidxTestExt = "1.3.0"
androidxTestOrchestrator = "1.6.1"
androidxTestRunner = "1.7.0"
androidxTextUiautomator = "2.3.0"
androidGradlePlugin = "9.0.0"
appcompat = "1.7.1"
authFoundation = "2.0.3"
bouncycastle = "1.83"
commonsIo = "2.21.0"
commons-lang3 = "3.20.0"
compatibilityValidator = "0.18.1"
coreKtx = "1.17.0"
coreLibraryDesugaring = "2.1.5"
coroutines = "1.10.2"
cucumberAndroid = "7.18.1"
detektGradlePlugin = "1.23.8"
dokkaBase = "2.2.0-Beta"
espresso = "3.7.0"
googleFirebaseCrashlyticsGradlePlugin = "3.0.6"
googleServicesGradlePlugin = "4.4.4"
gradleMavenPublish = "0.36.0"
hamcrest = "3.0"
jackson = "2.21.0"
jjwtApi = "0.13.0"
json = "20251224"
jsoup = "1.22.1"
junit = "4.13.2"
kotlin = "2.3.0"
kotlinBinaryCompatibility = "0.18.1"
kotlinSerialization = "1.10.0"
koverGradlePlugin = "0.9.4"
ksp = "2.3.4" # prefix with kotlin version.
ktorClient = "3.4.0"
leakcanary = "2.14"
lifecycle = "2.10.0"
material = "1.13.0"
mockitoCore = "5.21.0"
mockitoKotlin = "6.2.2"
mockk = "1.14.7"
navigation = "2.9.6"
netty = "4.1.124.Final"
okhttp = "5.3.2"
okio = "3.16.4"
oktaAuthn = "3.0.0"
oktaLegacyOidc = "1.3.4"
oktaManagement = "25.0.0"
protobufJava = "4.33.4"
robolectric = "4.16.1"
room = "2.8.4"
safeArgs = "2.9.6"
securityCrypto = "1.1.0"
snakeyaml = "2.5"
sonarqubeGradlePlugin = "7.2.2.6593"
spotless = "8.2.0"
sqlcipherAndroid = "4.13.0"
timber = "5.0.1"
truth = "1.4.5"
turbine = "1.2.1"
woodstoxCore = "7.1.1"
activityCompose = "1.12.2"
composeBom = "2026.01.00"

[libraries]
android-documentation-plugin = { module = "org.jetbrains.dokka:android-documentation-plugin", version.ref = "dokkaBase" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "androidxBiometric" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidxBrowser" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-credentials-credentials = { module = "androidx.credentials:credentials", version.ref = "androidxCredentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidxCredentials" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastorePreferences" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidxSqlite" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidxTest" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-navigation = { module = "androidx.navigation:navigation-testing", version.ref = "navigation" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxTestOrchestrator" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidxTextUiautomator" }
app-compat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
bcutil-jdk18on = { module = "org.bouncycastle:bcutil-jdk18on", version.ref = "bouncycastle" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-library-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "coreLibraryDesugaring" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
cucumber-android = { module = "io.cucumber:cucumber-android", version.ref = "cucumberAndroid" }
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokkaBase" }
dokka-core = { module = "org.jetbrains.dokka:dokka-core", version.ref = "dokkaBase" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }

espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
gradle-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradleMavenPublish" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwtApi" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwtApi" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwtApi" }
json = { module = "org.json:json", version.ref = "json" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-binary-compatibility-plugin = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinBinaryCompatibility" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlin-serialization-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "kotlinSerialization" }
kotlin-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClient" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClient" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorClient" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktorClient" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktorClient" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorClient" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClient" }

ktor-client-mock = { module = "io.ktor:ktor-client-mock" , version.ref = "ktorClient" }
ktor-client-mock-jvm = { module = "io.ktor:ktor-client-mock-jvm" , version.ref = "ktorClient" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClient" }

leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockwebserver3 = { module = "com.squareup.okhttp3:mockwebserver3", version.ref = "okhttp" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-safe-args-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
netty-codec-http = { module = "io.netty:netty-codec-http", version.ref = "netty" }
netty-codec-http2 = { module = "io.netty:netty-codec-http2", version.ref = "netty" }
netty-common = { module = "io.netty:netty-common", version.ref = "netty" }
netty-handler = { module = "io.netty:netty-handler", version.ref = "netty" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mock-web-server = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okhttp-tls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttp" }
okio-core = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-jvm = { module = "com.squareup.okio:okio-jvm", version.ref = "okio" }
okta-auth-foundation = { module = "com.okta.kotlin:auth-foundation", version.ref = "authFoundation" }
okta-authn-api = { module = "com.okta.authn.sdk:okta-authn-sdk-api", version.ref = "oktaAuthn" }
okta-authn-impl = { module = "com.okta.authn.sdk:okta-authn-sdk-impl", version.ref = "oktaAuthn" }
okta-legacy-oidc = { module = "com.okta.android:okta-oidc-android", version.ref = "oktaLegacyOidc" }
okta-management-sdk = { module = "com.okta.sdk:okta-sdk-impl", version.ref = "oktaManagement" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobufJava" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
sqlcipher-android = { module = "net.zetetic:sqlcipher-android", version.ref = "sqlcipherAndroid" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
woodstox-core = { module = "com.fasterxml.woodstox:woodstox-core", version.ref = "woodstoxCore" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.6.0-alpha01" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "safeArgs" }
androidx-room = { id = "androidx.room", version.ref = "room" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektGradlePlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaBase" }
google-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlyticsGradlePlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesGradlePlugin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "koverGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "compatibilityValidator" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqubeGradlePlugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
android-lint = { id = "com.android.lint", version.ref = "androidGradlePlugin" }

[bundles]
